services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: onye-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - onye-network

networks:
  onye-network:
    driver: bridge
