services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: onye-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - onye-network

networks:
  onye-network:
    driver: bridge
